# >------------------------------------------------------------------------------------------< #
# |  ____                 _       _____              _                                       | #
# | |  _ \               | |     / ____|            | |                                      | #
# | | |_) |  __ _  _ __  | | __ | (___   _   _  ___ | |_  ___  _ __ ___                      | #
# | |  _ <  / _` || '_ \ | |/ /  \___ \ | | | |/ __|| __|/ _ \| '_ ` _ \                     | #
# | | |_) || (_| || | | ||   <   ____) || |_| |\__ \| |_|  __/| | | | | |                    | #
# | |____/  \__,_||_| |_||_|\_\ |_____/  \__, ||___/ \__|\___||_| |_| |_|                    | #
# |                                       __/ |                                              | #
# |                                      |___/                                               | #
# |     by Daddel                                                                            | #
# |                                                                                          | #
# |   config.yml                                                                             | #
# |                                                                                          | #
# |   Version: 1.3                                                                           | #
# >------------------------------------------------------------------------------------------< #

# Have found an error or do you speak another language? Join the discord to share your knowledge: https://discord.gg/3uNxXcmRdp
# You can't add new languages! available languages: en_US, de_DE, nl_NL
language: en_US

# If it is set to true players with the permission "novabank.updatenotify" will receive a notification when the version is outdated.
update-check-ingame: true

# >------------------------------------------------< #
# |   ___    _  _____  _    ___    _    ___  ___   | #
# |  |   \  /_\|_   _|/_\  | _ )  /_\  / __|| __|  | #
# |  | |) |/ _ \ | | / _ \ | _ \ / _ \ \__ \| _|   | #
# |  |___//_/ \_\|_|/_/ \_\|___//_/ \_\|___/|___|  | #
# >------------------------------------------------< #
# Enable messages in the console if something changes in the database
console-logging: true

# MySQL required!!
# To use the database change the point "use" to "true" then connect your database with the plugin
# If the usage is set to false then configs are created automatically!
database:
  use: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password


# >--------------------< #
# |   ___  _   _  ___  | #
# |  / __|| | | ||_ _| | #
# | | (_ || |_| | | |  | #
# |  \___| \___/ |___| | #
# >--------------------< #

# Customize the /bank menu
gui:
  # Set to true if you want to enable the bank menu
  enabled: true
  # Set the inventory name of the menu
  title: "&9Bank"
  # Change the size of gui
  # Minimum size is 9
  # Maximum size is 54
  size: 27
  placeholder:
    # Display placeholder around the buttons
    use: true
    # Change the material if you would like to
    # default material: GRAY_STAINED_GLASS_PANE
    material: GRAY_STAINED_GLASS_PANE
    # Set the name for the placeholder
    # Use only color codes for an invisible name
    name: "&7"
  withdraw:
    # Set the name for the withdraw button in the menu
    title: "&4Withdraw"
    # Change the material for the withdraw button
    material: RED_CONCRETE
    # Set the display name for the withdraw button
    name: "&4Withdraw"
    # Add a description for the withdraw item
    # You can add multiple lines
    description:
      - "&7Withdraw money from your bank account"
  deposit:
    # Set the name for the deposit button in the menu
    title: "&aDeposit"
    # Change the material for the deposit button
    material: LIME_CONCRETE
    # Set the display name for the deposit button
    name: "&aDeposit"
    # Add a description for the deposit item
    # You can add multiple lines
    description:
      - "&7Deposit money to your bank account"
  profile:
    # Change the name of the profile item (head item)
    name: "&e%novabank_player_name%'s bank account money"
    # Change the description for the profile item
    # You can't add multiple lines!
    description:
      - "&7Your current balance is $%novabank_balance%"